pr:
  - master

trigger:
  - master
resources:
  repositories:
    - repository: ops-macpaw-io
      type: github
      name: MacPaw/ops-macpaw-io
      ref: refs/heads/master
      endpoint: MacPaw

variables:
  - group: composer
  - name: project
    value: macpaw
  - name: component
    value: libs
  - name: dockerTag
    value: $(Build.SourceBranchName)-$(Build.BuildNumber)

stages:
  - stage: main
    pool:
      name: default-ops
    displayName: Build & Deploy
    jobs:
      - template: azp/templates/build-service.yaml@ops-macpaw-io
        parameters:
          name: extendMockHTTPClient
          projectGCR: $(project)/$(component)
          image: extend-mock-http-client
          dockerFile: ./.infrastructure/Dockerfile
          targets:
            - cli
          command: ci-checks
          reports:
            composer-validate:
              file: composer-validate.txt
            phpcs:
              file: phpcs.xml
            phpunit:
              file: phpunit.xml
              overrides: --parameter prefix=/app
            phpstan:
              file: phpstan.xml
